-- ============================================================
-- 資料修正：把被「斷貨自動結案」鎖住的採購單放回派貨流程
--
-- 這支不改 schema、不改任何函式，只修一張單的 status 欄位。
-- 留成 migration 是為了讓正式庫的人工修正有跡可循（另一位工程師才追得到）。
--
-- ── 病症 ────────────────────────────────────────────────
-- `_refresh_po_status`（20260801000000_po_item_stockout.sql:386-399）有一個分支：
--     ELSIF v_stockout_cnt > 0 AND v_outstanding = 0 THEN
--       v_new_status := CASE WHEN v_total_received > 0 THEN 'closed' ELSE 'cancelled' END;
-- 三個條件同時成立就自動 closed：
--   ① 這張 PO 有品項被標斷貨　② 其餘品項都收齊　③ 有收到貨
-- 沒有人按任何按鈕 —— 是收貨（rpc_confirm_gr）當下自動觸發。
--
-- 當初的用意是「斷貨後別再卡在 partially_received」（同檔 :365-367 註解），
-- 出發點正確；但沒注意到 `partially_received` 同時是派貨需求 view 的通行證：
--     20260818000030_wave_transfer_join_by_id.sql:77
--       WHERE po.status = ANY (ARRAY['sent','partially_received','fully_received'])
-- `closed` 不在白名單 → 整張單「已經收到的貨」從派貨工作台消失、
-- 建不了撿貨波次 → 沒有 transfer → 客人取貨閘門五條路全不成立、
-- 月結也收不到這筆錢（月結來源是 transfers）。
--
-- 也就是說：**只要一張單有任一品項斷貨，其餘收齊的貨會在收貨的瞬間被一起鎖住。**
--
-- ── 本次修正的單 ────────────────────────────────────────
-- PO2607241023（共 3 項，訂 37 / 收 21）：
--   · G01059-01 中元普渡必備金澎湃保庇桶        訂 7  收 0  → 斷貨 2026-08-07 17:48
--   · G01061-01 中元普渡開跑中元限定拜拜鱈魚組  訂 9  收 0  → 斷貨 2026-08-07 17:47
--   · G01062-01 中元地表最強普渡包2026驚天動地  訂 21 收 21 → 收齊，就是被鎖住的這批
-- 影響：GRP-20260712-006 共 16 張客人訂單、21 件貨，自 8/07 起卡住無法取貨。
--
-- 為什麼是 partially_received 而不是 fully_received：
--   訂 37 收 21，不是全部到貨，寫 fully_received 會讓單據說謊。
--   partially_received 正是 `_refresh_po_status` 在沒有 closed 分支時本來就會給的
--   狀態（同檔 :391-392），而且一樣在派貨白名單內。
--
-- ── 安全性 ──────────────────────────────────────────────
-- · purchase_orders 只有一個 BEFORE UPDATE trigger（trg_touch_purchase_orders，
--   只更新 updated_at），沒有阻擋或連動邏輯
-- · WHERE 同時比對 po_no 與 status='closed' → 只命中這一張；重複執行無作用（冪等）
-- · 兩項斷貨品項的 stockout_at 不動 → 它們仍然是斷貨，不會被誤認為還在等貨
-- · 在沒有這張單的環境（staging / 新建庫）WHERE 不命中，等同 no-op
--
-- ── 已知副作用 ──────────────────────────────────────────
-- 1. 這張單回到「部分到貨」，採購單列表會重新出現「進貨」按鈕
-- 2. ⚠️ 之後若有人對它按收貨或調整已收量，_refresh_po_status 會再跑一次 → 又變回
--    closed（根因未修，在那之前都會這樣）。故修正後應儘快完成派貨。
-- 3. 派貨動作本身不會觸發 _refresh_po_status，派完不會自動變回去
--
-- ── 回滾 ────────────────────────────────────────────────
--   UPDATE purchase_orders SET status = 'closed'
--    WHERE po_no = 'PO2607241023' AND status = 'partially_received';
--
-- ── 根因待處理（本 PR 不動）────────────────────────────
-- 這是全站性的：2026-08-17 盤點出 440 組「貨進總倉沒派出」，
-- 1,260 件、895 張客人訂單、總倉少收 $94,585。
-- 根治方向是讓 `closed` 的單也能進派貨需求 view，但該狀態被十餘支
-- view / RPC 當閘門條件（20260812000000 檔頭已警告過），
-- 需另案評估、逐一比對，不在本次資料修正範圍。
-- ============================================================

UPDATE purchase_orders
   SET status     = 'partially_received',
       updated_at = NOW()
 WHERE po_no = 'PO2607241023'
   AND status = 'closed';
